apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acme-solver-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
spec:
  ingressClassName: nginx
  rules:
    - host: ${AZURE_DOMAIN_NAME}
      http:
        paths:
          - path: /\.well-known/acme-challenge/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ${AZURE_BROWSERLESS_SERVICE_NAME}
                port:
                  number: 3000
