apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: browserless-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    cert-manager.io/acme-challenge-type: "http01"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${AZURE_DOMAIN_NAME}
      secretName: ${AZURE_TLS_SECRET_NAME}
  rules:
    - host: ${AZURE_DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${AZURE_BROWSERLESS_SERVICE_NAME}
                port:
                  number: 3000
          - path: /websocket
            pathType: Prefix
            backend:
              service:
                name: ${AZURE_BROWSERLESS_SERVICE_NAME}
                port:
                  number: 50000
