apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: ${AZURE_RESOURCE_GROUP}
    service.beta.kubernetes.io/azure-pip-name: ${AZURE_INGRESS_PUBLIC_IP_NAME}
  name: ${AZURE_BROWSERLESS_SERVICE_NAME}
spec:
  type: LoadBalancer
  loadBalancerIP: ${INGRESS_IP}
  selector:
    app: browserless
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: ws
      port: 50000
      protocol: TCP
      targetPort: 50000
