properties:
  environmentId: ${AZURE_CONTAINER_APP_ENVIRONMENT_ID}
  configuration:
    ingress:
      external: true
      targetPort: 11977
      additionalPortMappings:
        - targetPort: 11978
          external: true
        - targetPort: 11979
          external: true
      traffic:
        - weight: 100
          latestRevision: true
  template:
    containers:
      - name: browserless
        resources:
          cpu: 1.0
          memory: 2Gi
